# Generated by Django 2.1.3 on 2018-12-04 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='B3a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('ty', models.CharField(max_length=3)),
                ('taxable_value', models.IntegerField()),
                ('total', models.IntegerField()),
                ('igst', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='B3b',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxable_value', models.IntegerField()),
                ('igst', models.IntegerField(null=True)),
                ('cgst', models.IntegerField(null=True)),
                ('sgst', models.IntegerField(null=True)),
                ('cess', models.IntegerField(null=True)),
                ('month', models.CharField(max_length=20)),
                ('ty', models.CharField(max_length=3)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('gstin', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('phn', models.CharField(max_length=11)),
                ('usr', models.CharField(max_length=10)),
                ('passwd', models.CharField(max_length=15)),
                ('mail', models.CharField(max_length=15)),
                ('pan', models.CharField(max_length=15)),
                ('provisional_id', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Client_extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('adhaar', models.CharField(max_length=20)),
                ('gstin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Client')),
            ],
        ),
        migrations.CreateModel(
            name='R1a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=8)),
                ('taxable_value', models.IntegerField()),
                ('cgst', models.IntegerField(null=True)),
                ('sgst', models.IntegerField(null=True)),
                ('igst', models.IntegerField(null=True)),
                ('cess', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('gstin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Client')),
            ],
        ),
        migrations.CreateModel(
            name='R1b',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('nil_supply_is', models.IntegerField(null=True)),
                ('nil_supply_ws', models.IntegerField(null=True)),
                ('non_gst_is', models.IntegerField(null=True)),
                ('non_gst_ws', models.IntegerField(null=True)),
                ('other_exempted_is', models.IntegerField(null=True)),
                ('other_exempted_ws', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('gstin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Client')),
            ],
        ),
        migrations.CreateModel(
            name='R2a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxable_value', models.IntegerField()),
                ('total', models.IntegerField()),
                ('igst', models.IntegerField(null=True)),
                ('cgst', models.IntegerField(null=True)),
                ('sgst', models.IntegerField(null=True)),
                ('cess', models.IntegerField(null=True)),
                ('month', models.CharField(max_length=20)),
                ('gstin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Client')),
            ],
        ),
        migrations.AddField(
            model_name='b3b',
            name='gstin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Client'),
        ),
        migrations.AddField(
            model_name='b3a',
            name='gstin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Client'),
        ),
    ]
