# Generated by Django 2.1.2 on 2018-11-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
