# Generated by Django 2.1.2 on 2018-11-05 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='B3a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('intypeb3a', models.CharField(max_length=20)),
                ('total_taxable_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='B3b',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intypeb3b', models.CharField(max_length=4)),
                ('total_taxable_value', models.IntegerField()),
                ('igst', models.IntegerField()),
                ('cgst', models.CharField(max_length=20)),
                ('sgst', models.IntegerField()),
                ('cess', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('gstin', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phn', models.CharField(max_length=11)),
                ('usr', models.CharField(max_length=10)),
                ('passwd', models.CharField(max_length=15)),
                ('mail', models.CharField(max_length=15)),
                ('pan', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Client_extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('adhaar', models.CharField(max_length=20)),
                ('gstin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Client')),
            ],
        ),
        migrations.CreateModel(
            name='R1a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstinb', models.CharField(max_length=15)),
                ('month', models.CharField(max_length=8)),
                ('invoice_no', models.IntegerField()),
                ('cust_name', models.CharField(max_length=20)),
                ('state_of_supply', models.CharField(max_length=15)),
                ('invoice_date', models.DateField()),
                ('invoice_value', models.IntegerField()),
                ('tax_rate', models.IntegerField()),
                ('taxable_value', models.IntegerField()),
                ('cgst', models.IntegerField()),
                ('sgst', models.IntegerField()),
                ('igst', models.IntegerField()),
                ('cess', models.IntegerField()),
                ('gstin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Client')),
            ],
        ),
        migrations.CreateModel(
            name='R1b',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstinb', models.CharField(max_length=15)),
                ('quarter', models.CharField(max_length=20)),
                ('nil_supply_is', models.IntegerField()),
                ('nil_supply_ws', models.IntegerField()),
                ('non_gst_is', models.IntegerField()),
                ('non_gst_ws', models.IntegerField()),
                ('other_exempted_is', models.IntegerField()),
                ('other_exempted_ws', models.IntegerField()),
                ('gstin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Client')),
            ],
        ),
        migrations.CreateModel(
            name='R2a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intyper2a', models.CharField(max_length=4)),
                ('invoice_no', models.IntegerField()),
                ('invoice_value', models.IntegerField()),
                ('tax_rate', models.IntegerField()),
                ('taxable_value', models.IntegerField()),
                ('total_taxable_value', models.IntegerField()),
                ('igst', models.IntegerField()),
                ('cgst', models.CharField(max_length=20)),
                ('sgst', models.IntegerField()),
                ('cess', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('gstin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Client')),
            ],
        ),
        migrations.AddField(
            model_name='b3b',
            name='gstin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Client'),
        ),
        migrations.AddField(
            model_name='b3a',
            name='gstin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Client'),
        ),
    ]
