# Generated by Django 2.1.2 on 2018-11-01 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('gstin', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phn', models.CharField(max_length=11)),
                ('usr', models.CharField(max_length=10)),
                ('passwd', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=254)),
                ('pan', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='R1a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstinb', models.CharField(max_length=15)),
                ('gstin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Client')),
            ],
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
