# Generated by Django 2.1.2 on 2018-11-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20181101_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mail',
        ),
    ]
